// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package datab

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.insertCommentStmt, err = db.PrepareContext(ctx, insertComment); err != nil {
		return nil, fmt.Errorf("error preparing query InsertComment: %w", err)
	}
	if q.insertPostStmt, err = db.PrepareContext(ctx, insertPost); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPost: %w", err)
	}
	if q.queryGetAllPostStmt, err = db.PrepareContext(ctx, queryGetAllPost); err != nil {
		return nil, fmt.Errorf("error preparing query QueryGetAllPost: %w", err)
	}
	if q.queryGetCommentByIdStmt, err = db.PrepareContext(ctx, queryGetCommentById); err != nil {
		return nil, fmt.Errorf("error preparing query QueryGetCommentById: %w", err)
	}
	if q.queryGetPostByIdStmt, err = db.PrepareContext(ctx, queryGetPostById); err != nil {
		return nil, fmt.Errorf("error preparing query QueryGetPostById: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.insertCommentStmt != nil {
		if cerr := q.insertCommentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertCommentStmt: %w", cerr)
		}
	}
	if q.insertPostStmt != nil {
		if cerr := q.insertPostStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPostStmt: %w", cerr)
		}
	}
	if q.queryGetAllPostStmt != nil {
		if cerr := q.queryGetAllPostStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing queryGetAllPostStmt: %w", cerr)
		}
	}
	if q.queryGetCommentByIdStmt != nil {
		if cerr := q.queryGetCommentByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing queryGetCommentByIdStmt: %w", cerr)
		}
	}
	if q.queryGetPostByIdStmt != nil {
		if cerr := q.queryGetPostByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing queryGetPostByIdStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                      DBTX
	tx                      *sql.Tx
	insertCommentStmt       *sql.Stmt
	insertPostStmt          *sql.Stmt
	queryGetAllPostStmt     *sql.Stmt
	queryGetCommentByIdStmt *sql.Stmt
	queryGetPostByIdStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                      tx,
		tx:                      tx,
		insertCommentStmt:       q.insertCommentStmt,
		insertPostStmt:          q.insertPostStmt,
		queryGetAllPostStmt:     q.queryGetAllPostStmt,
		queryGetCommentByIdStmt: q.queryGetCommentByIdStmt,
		queryGetPostByIdStmt:    q.queryGetPostByIdStmt,
	}
}
