// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package datab

import (
	"database/sql"
	"time"
)

type Comment struct {
	Commentid      int32          `json:"commentid"`
	Commentpostid  sql.NullInt32  `json:"commentpostid"`
	Commentdesc    string         `json:"commentdesc"`
	Commentuser    sql.NullString `json:"commentuser"`
	Commentcreated time.Time      `json:"commentcreated"`
}

type Post struct {
	Postid         int32        `json:"postid"`
	Username       string       `json:"username"`
	Title          string       `json:"title"`
	Posdescription string       `json:"posdescription"`
	Created        sql.NullTime `json:"created"`
}
