// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package datab

import (
	"context"
	"database/sql"
	"time"
)

const insertComment = `-- name: InsertComment :exec
insert into "comments" (commentPostId,commentDesc,commentUser,commentCreated) values ($1,$2,$3,$4)
`

type InsertCommentParams struct {
	Commentpostid  int32  `json:"commentpostid"`
	Commentdesc    string         `json:"commentdesc"`
	Commentuser    string `json:"commentuser"`
	Commentcreated time.Time      `json:"commentcreated"`
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.exec(ctx, q.insertCommentStmt, insertComment,
		arg.Commentpostid,
		arg.Commentdesc,
		arg.Commentuser,
		arg.Commentcreated,
	)
	return err
}

const insertPost = `-- name: InsertPost :exec
INSERT INTO posts(userName,title,posDescription,created) values($1,$2,$3,$4)
`

type InsertPostParams struct {
	Username       string       `json:"username"`
	Title          string       `json:"title"`
	Posdescription string       `json:"posdescription"`
	Created        sql.NullTime `json:"created"`
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) error {
	_, err := q.exec(ctx, q.insertPostStmt, insertPost,
		arg.Username,
		arg.Title,
		arg.Posdescription,
		arg.Created,
	)

	return err
}

const queryGetAllPost = `-- name: QueryGetAllPost :many
SELECT postid, username, title, posdescription, created FROM posts
`

func (q *Queries) QueryGetAllPost(ctx context.Context) ([]Post, error) {
	rows, err := q.query(ctx, q.queryGetAllPostStmt, queryGetAllPost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.Postid,
			&i.Username,
			&i.Title,
			&i.Posdescription,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryGetCommentById = `-- name: QueryGetCommentById :many
SELECT commentid, commentpostid, commentdesc, commentuser, commentcreated FROM "comments" where commentPostId = $1
`

func (q *Queries) QueryGetCommentById(ctx context.Context, commentpostid sql.NullInt32) ([]Comment, error) {
	rows, err := q.query(ctx, q.queryGetCommentByIdStmt, queryGetCommentById, commentpostid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.Commentid,
			&i.Commentpostid,
			&i.Commentdesc,
			&i.Commentuser,
			&i.Commentcreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryGetPostById = `-- name: QueryGetPostById :one
SELECT postid, username, title, posdescription, created FROM "posts" where postId = $1
`

func (q *Queries) QueryGetPostById(ctx context.Context, postid int32) (Post, error) {
	row := q.queryRow(ctx, q.queryGetPostByIdStmt, queryGetPostById, postid)
	var i Post
	err := row.Scan(
		&i.Postid,
		&i.Username,
		&i.Title,
		&i.Posdescription,
		&i.Created,
	)
	return i, err
}
